### ISSUE TITLE
[High Priority] New Functionality: Ability to remove news and events from the News & Events page 

### ISSUE THREAD

**Issue by nicudy** [seng426-team3/vega-web#2]
Estimation: 15 points
Actual effort: 8 points

Admin and staff users should be able to remove newsletters and events from the news & events page so that they can remove unwanted or no longer wanted posts. 

1. When an admin user navigates to the news & events page, they can click on a “x” icon to remove a post.
2.  A window should appear that asks them to confirm that they would like to delete the post.
3. They can then click the "confirm" button that deletes the post.
4. They can now no longer see the removed post on the news & events page.
5. No users can see the removed post on the news & events page.

**Comment by kianapaz** [comment]
Closing with time estimation 6 hours.
