### ISSUE TITLE
[ZAP] Reflected XSS Weakness in JSON Response

### ISSUE THREAD

**Issue by BrodyGimson** [seng426-team3/vega-web#55]
Create secret route from backend found to have a reflected XSS weakness. ZAP priority is Low as the confidence level for the issue is low. Look at reproducing issue manually first.

**Comment by JesseLacroix** [comment]
Could not reproduce with manual testing on create secret, looked at the code and any sql statements that may be injected to the table from the create secret input seem to be prevented by how the data is stored into the database when created
