### ISSUE TITLE
[ZAP] Persistent XSS Weakness in JSON Response

### ISSUE THREAD

**Issue by BrodyGimson** [seng426-team3/vega-web#56]
The routes for fetchcontactus and fetchallsecrets in the backend can lead to an XSS attack if the user does not process the response properly.

**Comment by skosman** [comment]
For fetchcontactus, the data from the response are inserted into the page using {} in react. By default, React DOM escapes any values embedded in this form, converting them to a string before being rendered preventing XSS. Link: https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks. This was tested by passing <script>alert(1);</script> into a field and it just returns the string of it.

**Comment by skosman** [comment]
For fetch all secrets, we use ag-grid to display the data. This is sanitized before displaying them to stop xss and was tested again by passing <script>alert(1);</script> into the field. Data was not sanitized for [versions <14](https://github.com/advisories/GHSA-7p6w-x2gr-rrf8), however we are using version 27.3.0 which does.
