### ISSUE TITLE
[ZAP] Format String Error

### ISSUE THREAD

**Issue by BrodyGimson** [seng426-team3/vega-web#58]
The routes /upload and /vault/createsecret in the backend have potential string formatting issues. Occurs when the input string is evaluated as a command by the application. ZAP priority Medium.

**Comment by kianapaz** [comment]
I've been looking into this error, and the path traversal for the routes look to be a false positive. I can continue to investigate, but it looks to be good too close.

**Comment by kianapaz** [comment]
Ran manual testing: Found that when re-formatting the route for /upload it returned a 403 forbidden error as a page visitor. While trying to add files as a staff, it returned a 403 code, and only displayed the resources uploaded by the admin. The admin was the only one able to successfully upload.

**Comment by kianapaz** [comment]
Ran manual testing for the route /vault/createsecret: Returned a 404 error as a page visitor and so the string was not formatted as a command. Users, staff and admin are permitted to access this page, but reformatting the string was not executed as a command.
These route format string error issues were a false positive as the backend didn't parse the string as a command, and only returned an error as the user's were not authenticated. The users that were permitted to view the site could access the route, but not execute a command.
